version: "3.7"
services:
  simbotic-ros-gpu:
    build:
      context: .
      dockerfile: Dockerfile.gpu
      args:
        - USER_ID
        - GROUP_ID
      network: host
    image: simbotic-ros/gpu:v0.0.1
